<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_messageGroup</name>
   <tag></tag>
   <elementGuidId>112171ee-c541-43ba-9401-b3b4dfbb326d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#scrollableDiv >> internal:label=&quot;TEST TASK&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a9407b8-0944-4c00-b744-ccf7599b8c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAvatar-root MuiAvatar-circular MuiAvatar-colorDefault hover:rounded !rounded css-baskcj-MuiAvatar-root</value>
      <webElementGuid>516f4096-81e9-4bb9-a1a2-f915665653dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shadow</name>
      <type>Main</type>
      <value>xl</value>
      <webElementGuid>1451e987-5f20-4c7b-9dd5-48f032196a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>d</value>
      <webElementGuid>564aa42b-146b-491d-aace-627c63619226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollableDiv&quot;)/div[@class=&quot;group_thumball flex justify-center items-center max-w-16 h-16 text-white hover:bg-sky-600&quot;]/a[@class=&quot;bg-sky-600&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary css-1vqs9o7-MuiButtonBase-root-MuiButton-root&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-circular MuiAvatar-colorDefault hover:rounded !rounded css-baskcj-MuiAvatar-root&quot;]</value>
      <webElementGuid>95805252-a776-4b44-8846-68ab2291387b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollableDiv']/div/a/button/div</value>
      <webElementGuid>6bcc1045-a086-4068-8bd8-20911223af1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST TASK'])[1]/preceding::div[5]</value>
      <webElementGuid>e4ccecd6-9ac7-4278-b623-954a7cb2c5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuộc trò chuyện chung'])[1]/preceding::div[8]</value>
      <webElementGuid>d65fa0c5-4af8-476e-ab1a-a879ec003df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='d']/parent::*</value>
      <webElementGuid>d763539e-d253-426a-82c6-f4bdc65c590a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button/div</value>
      <webElementGuid>8f004c5c-8c79-45cb-83c4-4cc07d13496d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'd' or . = 'd')]</value>
      <webElementGuid>cf34500d-31f1-49e9-bdee-d74dd29097b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
