<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_quyenQuanLyBangTin</name>
   <tag></tag>
   <elementGuidId>3cf70f43-886c-422c-80ca-bf60ad24273f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Quyền quản lý bảng tin&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a908b346-8348-48a5-a5dd-d61706e58f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5a329757-7c95-4ef1-b003-91bae1acc07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7f6ed9c6-8202-4bba-b903-eb55235b2a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rt:-option-3</value>
      <webElementGuid>c95333c1-55f0-4a73-bfd2-656c4cb23772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>60ee3650-6fe8-4362-94a4-72383becb7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b216d680-3206-4d63-8825-ff3617745e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9fcd0535-fad8-42fd-b74e-b35f4347b2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>6777f8bb-21ea-4ffb-b9dc-9b36125ec965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quyền quản lý bảng tin</value>
      <webElementGuid>00f7d403-6896-4402-94e3-e733f6dab6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rt:-option-3&quot;)</value>
      <webElementGuid>5d3d6933-5740-437e-a069-770ed0c9b22b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id=':rt:-option-3']</value>
      <webElementGuid>67a04e88-f047-4151-94f6-cf943bbede4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id=':rt:-listbox']/li[4]</value>
      <webElementGuid>1ad4083e-cf95-436d-9748-ce4fe5a79c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quyền quản lý lịch hẹn'])[2]/following::li[1]</value>
      <webElementGuid>82f060fa-450d-4a6c-8475-0c9d69aa5dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quyền quản lí công việc'])[2]/following::li[2]</value>
      <webElementGuid>bfbd5d9f-d4c1-4a56-b583-a03d3eb3420c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quyền quản lý câu hỏi thường gặp'])[1]/preceding::li[1]</value>
      <webElementGuid>9c842bf4-d896-4966-99b4-6ff06ad84a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quyền cài đặt nhóm'])[1]/preceding::li[2]</value>
      <webElementGuid>3583bfcd-d762-4475-8226-1268e532e55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quyền quản lý bảng tin']/parent::*</value>
      <webElementGuid>afb211c5-f06a-4655-baf8-83a8b024c464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>4f0cb7cd-ae35-4315-a61d-84f7735d7d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = ':rt:-option-3' and (text() = 'Quyền quản lý bảng tin' or . = 'Quyền quản lý bảng tin')]</value>
      <webElementGuid>40139979-e65a-4b0e-9eb6-1ffc2df95238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
