<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_quyenQuanLyCauHoiThuongGap</name>
   <tag></tag>
   <elementGuidId>e01da6f5-99ce-4339-9ba7-eea39e1f2471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Quyền quản lý câu hỏi thường gặp&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>416d8fbd-6bbd-41d3-a766-f4595e550e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8abcfdab-fd3e-4f79-99be-d963b5598c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>950df5d2-b8c1-4428-bdab-e66840716713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rt:-option-4</value>
      <webElementGuid>1e85c98d-d80a-40e3-9dc3-aa4fd6765fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f435e661-8e46-49c8-ad7d-2796d73b5329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d28e2490-4bf2-4186-80f9-58df0f94af75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2977db9f-cdf8-4d9b-9ce9-b76c9b267311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>2ddec63d-8b71-4480-ae7b-14a09999681f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quyền quản lý câu hỏi thường gặp</value>
      <webElementGuid>eb14ac32-7fd4-4c1b-86b5-0bc121a68810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rt:-option-4&quot;)</value>
      <webElementGuid>4863c2c6-0495-4906-8b5f-c4525678cd19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id=':rt:-option-4']</value>
      <webElementGuid>8eaaf957-df35-4a86-926b-5bdcd2b0a60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id=':rt:-listbox']/li[5]</value>
      <webElementGuid>b7df65a3-0821-4fe7-9df5-ea972de604c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quyền quản lý bảng tin'])[1]/following::li[1]</value>
      <webElementGuid>86f6cf7b-bab4-4dae-a966-e6d9f00320aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quyền quản lý lịch hẹn'])[2]/following::li[2]</value>
      <webElementGuid>3e6a2af8-0004-4c0c-9596-9ab4db8e7ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quyền cài đặt nhóm'])[1]/preceding::li[1]</value>
      <webElementGuid>7d1860b4-bfd6-4554-a260-884745c2ce44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quyền quản lý câu hỏi thường gặp']/parent::*</value>
      <webElementGuid>17320ce0-327f-46ae-8151-8a51515d1bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]</value>
      <webElementGuid>68300ac7-04ba-4a64-a3f6-a67ca464f97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = ':rt:-option-4' and (text() = 'Quyền quản lý câu hỏi thường gặp' or . = 'Quyền quản lý câu hỏi thường gặp')]</value>
      <webElementGuid>9b07919b-0bfa-498d-9c29-cdd7613770f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
