<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_text_empty_assignee</name>
   <tag></tag>
   <elementGuidId>b459cbb9-dc78-4a78-ac04-bec30c8fcd8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Vui lòng chọn người sẽ thực hiện công việc&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>02d080e1-0a91-40b4-8b6e-732827ccc9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained Mui-focused css-o1ds8i-MuiFormHelperText-root</value>
      <webElementGuid>b69cf897-e4ff-457c-92f5-6f6a6eba52fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r5g:-helper-text</value>
      <webElementGuid>12c9e806-04cd-4c61-8500-a4b05d2fbe5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vui lòng chọn người sẽ thực hiện công việc</value>
      <webElementGuid>3dfc3295-f064-4674-a603-498dccec6f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r5g:-helper-text&quot;)</value>
      <webElementGuid>5f506599-2293-4162-8b85-1cfe399bc9e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r5g:-helper-text']</value>
      <webElementGuid>5d2bfa2e-118b-44a2-ad79-67420c54d03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giao công việc (*)'])[2]/following::p[1]</value>
      <webElementGuid>d9c41f29-0d30-4d06-b8f6-368667880044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giao công việc (*)'])[1]/following::p[1]</value>
      <webElementGuid>5d796280-a0f9-49a9-8570-c1f183d2f365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đóng'])[1]/preceding::p[1]</value>
      <webElementGuid>8c6542f5-625c-4272-b7b5-b1dec6d6d8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo công việc'])[1]/preceding::p[1]</value>
      <webElementGuid>feec4398-b799-4d8d-92e3-dc1eb7c4889e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vui lòng chọn người sẽ thực hiện công việc']/parent::*</value>
      <webElementGuid>a01bb18d-2c70-4975-82be-d1acef0f18b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/p</value>
      <webElementGuid>b5732f91-1bfc-4ae8-8041-293ef311ccf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r5g:-helper-text' and (text() = 'Vui lòng chọn người sẽ thực hiện công việc' or . = 'Vui lòng chọn người sẽ thực hiện công việc')]</value>
      <webElementGuid>afbd9273-eb16-4846-a95f-29da84579210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
