<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_text_date</name>
   <tag></tag>
   <elementGuidId>671fabf8-2bde-4d69-8af9-5eb519303cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ngày tới hạn phải lớn hơn hoặc bằng ngày hiện tại&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dfbb0385-e789-4562-b531-d0b63c53cd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained MuiFormHelperText-filled css-o1ds8i-MuiFormHelperText-root</value>
      <webElementGuid>f2fd87f4-c069-42b2-ae69-6c5bda6faef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r5e:-helper-text</value>
      <webElementGuid>cd6708c7-97d4-4c3f-b451-81a1b7eee6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ngày tới hạn phải lớn hơn hoặc bằng ngày hiện tại</value>
      <webElementGuid>6af60e7a-7b00-4178-a03d-2f81fc635c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r5e:-helper-text&quot;)</value>
      <webElementGuid>f8e5efec-210c-41b0-8763-21a25ba15bde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r5e:-helper-text']</value>
      <webElementGuid>ff494efe-2777-42cf-b40a-fa8b9a26ec05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày (*)'])[2]/following::p[1]</value>
      <webElementGuid>a006a78f-3d9b-4a40-91df-5fd12bd10e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày (*)'])[1]/following::p[1]</value>
      <webElementGuid>41279ceb-b591-4d3b-8a1f-b250dbe237e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giao công việc (*)'])[1]/preceding::p[1]</value>
      <webElementGuid>2c8518ee-593a-4689-bc0f-666f6be950b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giao công việc (*)'])[2]/preceding::p[1]</value>
      <webElementGuid>2127c7f5-afcd-4b00-ba9c-cc88f26a70a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ngày tới hạn phải lớn hơn hoặc bằng ngày hiện tại']/parent::*</value>
      <webElementGuid>d06d2b70-67d3-462b-b16d-6db3fcce96c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>754adb84-b6b9-47be-a036-ece0c022c0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r5e:-helper-text' and (text() = 'Ngày tới hạn phải lớn hơn hoặc bằng ngày hiện tại' or . = 'Ngày tới hạn phải lớn hơn hoặc bằng ngày hiện tại')]</value>
      <webElementGuid>c61b311a-d6c9-4700-a49f-69e709656618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
