<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_1</name>
   <tag></tag>
   <elementGuidId>13d9a4eb-ef65-4acb-b30e-1c47f78ca921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Nguyễn Văn A B C D E F G H I J K L M N O P Q R SAN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>56f93be8-5976-4c75-93a2-45f3f90f8b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiListItem-root MuiListItem-padding MuiAutocomplete-option css-1l3ki7u-MuiListItem-root Mui-focused</value>
      <webElementGuid>d34d7144-f627-4b91-a2d2-43ba5c4b5f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e85c9039-126f-4e43-acc5-4ac1da154917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cecc1a92-b946-4d8b-bc26-8ef691ced643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r53:-option-0</value>
      <webElementGuid>e6d3323c-6355-40e1-8b50-accf509646f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>91af88c9-0583-45d8-9c07-5399273900fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1bcf53c-c899-4849-9531-b7386eafc5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e63c47c0-da4d-41d7-aa3c-d984d4d76b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nguyễn Văn A B C D E F G H I J K L M N O P Q R SAN</value>
      <webElementGuid>cfe2a533-3a1c-432a-8c06-2b4bc941287b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r53:-option-0&quot;)</value>
      <webElementGuid>5e6553ba-cbe6-47e8-8ceb-36101dd149c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id=':r53:-option-0']</value>
      <webElementGuid>32a21331-c4b6-4f4f-89ca-c07c1d5ff11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id=':r53:-listbox']/li</value>
      <webElementGuid>25a5f94a-f469-4abe-8042-4cdb2d4e79b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo công việc'])[1]/following::li[1]</value>
      <webElementGuid>d04e7be8-06cb-4b0f-a892-bfef6d702560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đóng'])[1]/following::li[1]</value>
      <webElementGuid>4db72331-3ec5-44bb-a656-c3c8ac8007a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uyen Nhi'])[1]/preceding::li[1]</value>
      <webElementGuid>771172a4-87ef-4d14-a50b-617b85adbb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>0780f7ba-293f-414a-b1f2-b91b5f108b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = ':r53:-option-0' and (text() = 'Nguyễn Văn A B C D E F G H I J K L M N O P Q R SAN' or . = 'Nguyễn Văn A B C D E F G H I J K L M N O P Q R SAN')]</value>
      <webElementGuid>6ad63975-9ea2-40e3-b223-2424b51ce67a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
